# ==========================================================
# Smart Equipment Booking & Maintenance System
# Spring Boot Configuration
# ==========================================================

server.port=8080
spring.application.name=smart-equipment-backend

# Local PostgreSQL Database Connection (Ultra-Fast 0ms Latency)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_equipment_db
spring.datasource.username=postgres
spring.datasource.password=Medi@2023
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false

# HikariCP Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Date Time format in JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Colombo

# JWT Security Configurations
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
