# ==========================================================
# Smart Equipment Booking & Maintenance System
# Spring Boot Configuration
# ==========================================================

server.port=8080
spring.application.name=smart-equipment-backend

# Neon Cloud PostgreSQL Database Connection (Shared for both partners)
spring.datasource.url=jdbc:postgresql://ep-green-unit-az5numnl-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KeHX82rjCkxO
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Date Time format in JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Colombo
